config/routes.rb
Rails.application.routes.draw do
  resources :items do
    get ":transaction_type", on: :new, to: "items#new", as: :new_item
  end
  resources :categories
  resources :payment_types
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "items#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items

  validates_presence_of :name
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :payment_type
  belongs_to :transaction_type
  belongs_to :category

  validates_presence_of :amount
end

app/models/item_category.rb
class ItemCategory < ApplicationRecord
  belongs_to :item
  belongs_to :category

  validates :category_id, uniqueness: { scope: :item_id }
end

app/models/payment_type.rb
class PaymentType < ApplicationRecord
  has_many :items

  validates_presence_of :name
end

app/models/transaction_type.rb
class TransactionType < ApplicationRecord
  has_many :items

  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy!

    respond_to do |format|
      format.html { redirect_to categories_path, status: :see_other, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.expect(category: [ :name ])
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]

  # GET /items or /items.json
  def index
    @items = Item.all
  end

  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
    if params[:transaction_type] == "income"
      @item.transaction_type = TransactionType.find_by(name: "Prihod")
    elsif params[:transaction_type] == "expense"
      @item.transaction_type = TransactionType.find_by(name: "Rashod")
    elsif params[:transaction_type] == "transfer"
      @item.transaction_type = TransactionType.find_by(name: "Prijenos")
    else
      @item.errors
    end
    @item.event_date = Time.now.strftime('%Y.%m.%d. %I:%M:%S %p')
    @item.payment_date = Time.now.strftime('%Y.%m.%d. %I:%M:%S %p')
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to items_url, notice: "Item was successfully created." }
        format.json { render :index, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy!

    respond_to do |format|
      format.html { redirect_to items_path, status: :see_other, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params
        .require(:item)
        .permit(
          :payment_type_id,
          :transaction_type_id,
          :category_id,
          :note,
          :amount,
          :event_date,
          :payment_date
        )
    end
end

app/controllers/payment_types_controller.rb
class PaymentTypesController < ApplicationController
  before_action :set_payment_type, only: %i[ show edit update destroy ]

  # GET /payment_types or /payment_types.json
  def index
    @payment_types = PaymentType.all
  end

  # GET /payment_types/1 or /payment_types/1.json
  def show
  end

  # GET /payment_types/new
  def new
    @payment_type = PaymentType.new
  end

  # GET /payment_types/1/edit
  def edit
  end

  # POST /payment_types or /payment_types.json
  def create
    @payment_type = PaymentType.new(payment_type_params)

    respond_to do |format|
      if @payment_type.save
        format.html { redirect_to @payment_type, notice: "Payment type was successfully created." }
        format.json { render :show, status: :created, location: @payment_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @payment_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payment_types/1 or /payment_types/1.json
  def update
    respond_to do |format|
      if @payment_type.update(payment_type_params)
        format.html { redirect_to @payment_type, notice: "Payment type was successfully updated." }
        format.json { render :show, status: :ok, location: @payment_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @payment_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payment_types/1 or /payment_types/1.json
  def destroy
    @payment_type.destroy!

    respond_to do |format|
      format.html { redirect_to payment_types_path, status: :see_other, notice: "Payment type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment_type
      @payment_type = PaymentType.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def payment_type_params
      params.expect(payment_type: [ :name ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/payment_types_helper.rb
module PaymentTypesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.textarea :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<% content_for :title, "Editing category" %>

<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Categories" %>

<h1>Categories</h1>

<div id="categories">
  <% @categories.each do |category| %>
    <%= render category %>
    <p>
      <%= link_to "Show this category", category %>
    </p>
  <% end %>
</div>

<%= link_to "New category", new_category_path %>

app/views/categories/new.html.erb
<% content_for :title, "New category" %>

<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/items/_form.html.erb
<script>
	function clearDate() {
		console.log($(this.event.target).parent().siblings('.datetime-field').val(''));
	}

	$(document).ready(function() {
		$('#category-select').select2({
			selectionCssClass: 'select2-category-select'
		});
	});
</script>

<%= form_with(model: item) do |form| %>
	<% if item.errors.any? %>
		<div style="color: red">
			<h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

			<ul>
				<% item.errors.each do |error| %>
					<li><%= error.full_message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="mb-4">
		<%= form.label(:category_id, "Kategorija", class: "form-label") %>
		<%= form.collection_select(
			:category_id,
			Category.left_joins(:items)
				.group(:id)
				.order('COUNT(items.id) DESC, categories.name ASC'),
			:id,
			:name,
			{},
			{
				id: "category-select",
				class: "form-select"
			}
		) %>
	</div>

	<div class="mb-4">
		<%= form.label(:amount, "Iznos", class: "form-label") %>
		<div class="input-group">
			<%= form.number_field :amount, class: "form-control" %>
			<span class="input-group-text">€</span>
		</div>
	</div>

	<div class="mb-4">
		<%= form.label(:payment_type_id, "Sredstvo", class: "form-label") %>
		<%= form.collection_select(
			:payment_type_id,
			if item.transaction_type.name == "Prihod" || item.transaction_type.name == "Rashod"
				PaymentType.where(name: "Kartica")
					.or(PaymentType.where(name: "Gotovina"))
					.or(PaymentType.where(name: "Revolut"))
			else
				PaymentType.where(name: "Prijenos na Revolut")
					.or(PaymentType.where(name: "Podizanje gotovine"))
					.or(PaymentType.where(name: "Uplata gotovine"))
			end,
			:id,
			:name,
			{ selected: PaymentType.find_by(name: "Kartica") },
			{ class: "form-select" }
		) %>
	</div>

	<div class="mb-4">
		<%= form.label(:note, "Napomena", class: "form-label") %>
		<%= form.text_field :note, class: "form-control" %>
	</div>

	<div class="mb-4">
		<%= form.label(:event_date, "Datum događaja", class: "form-label") %>
		<div class="datetime-container">
			<%= form.datetime_field :event_date, class: "form-control datetime-field" %>
			<span class="clear-button">
				<a class="btn btn-outline-secondary fa-solid fa-xmark" onclick="clearDate()"></a>
			</span>
		</div>
	</div>

	<div class="mb-4">
		<%= form.label(:payment_date, "Datum plaćanja", class: "form-label") %>
		<div class="datetime-container">
			<%= form.datetime_field :payment_date, class: "form-control datetime-field" %>
			<span class="clear-button">
				<a class="btn btn-outline-secondary fa-solid fa-xmark" onclick="clearDate()"></a>
			</span>
		</div>
	</div>

	<div class="action-button-group">
		<%= link_to "Poništi", items_path, class: "btn btn-secondary" %>
		<%= form.submit(class: "btn btn-primary", value: "Spremi") %>
	</div>

	<%= form.hidden_field :transaction_type_id %>
<% end %>

app/views/items/_item.html.erb
<div id="<%= dom_id item %>">
  <div class="item-content">
    <div class="item-content-category">
      <%#= item.category.name %>
      Sjednica općinskog vijeća Općine Kostrena
    </div>
    <div class="item-content-edit-img">
      <%= link_to edit_item_path(item), class: "edit-item-icon" do %>
        <i class="fa fa-edit"></i>
      <% end %>
    </div>
    <div class="item-content-paymentType">
      <%#= item.payment_type.name %>
      Prijenos na Revolut
    </div>
    <div class="item-content-amount-<%= item.transaction_type.name %>">
      <%= sprintf('%.2f', item.amount) %> €
    </div>
    <div class="item-content-note">
      <%#= item.note %>
      Predstavljanje kandidacijskih lista i sučeljavanje za izbor općinskog vijeća
    </div>
    <div class="item-content-eventDate-text">
      Datum događaja:
    </div>
    <div class="item-content-eventDate">
      <%= item.event_date.strftime('%d.%m.%Y. %I:%M:%S %p') %>
    </div>
    <div class="item-content-paymentDate-text">
      Datum plaćanja:
    </div>
    <div class="item-content-paymentDate">
      <%= item.payment_date.strftime('%d.%m.%Y. %I:%M:%S %p') %>
    </div>
  </div>
</div>

app/views/items/edit.html.erb
<div class="m-4">
	<h1 class="mb-4">Uređivanje stavke</h1>

	<%= render "form", item: @item %>
</div>

app/views/items/index.html.erb
<p style="color: green"><%= notice %></p>

<div id="items" class="items-container">
  <% @items.each do |item| %>
    <%= render item %>
  <% end %>
</div>

<%= render "layouts/floating_buttons" %>

app/views/items/new.html.erb
<div class="m-4">
  <h1 class="mb-4">Nova stavka</h1>

  <%= render "form", item: @item %>
</div>

app/views/items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @item %>

<div>
  <%= link_to "Edit this item", edit_item_path(@item) %> |
  <%= link_to "Back to items", items_path %>

  <%= button_to "Destroy this item", @item, method: :delete %>
</div>

app/views/layouts/_floating_buttons.html.erb
<div class="floating-buttons-wrapper">
  <div class="floating-buttons-gradient"></div>
  <div class="floating-buttons-container">
		<%= link_to new_item_new_item_path("transfer"), class: "btn btn-transfer" do %>
			<i class="fa fa-money-bill-transfer"></i>
		<% end %>
		<%= link_to new_item_new_item_path("income"), class: "btn btn-income" do %>
			<i class="fa fa-dollar-sign"></i>
		<% end %>
		<%= link_to new_item_new_item_path("expense"), class: "btn btn-expense" do %>
			<i class="fa fa-arrow-trend-down"></i>
		<% end %>
	</div>
</div>

app/views/layouts/_footer.html.erb
<div>
	prd smrd
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= content_for(:title) || "Finances" %></title>
		<meta name="viewport" content="width=device-width,initial-scale=1">
		<meta name="apple-mobile-web-app-capable" content="yes">
		<meta name="mobile-web-app-capable" content="yes">
		<%= csrf_meta_tags %>
		<%= csp_meta_tag %>

		<%= yield :head %>

		<%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
		<%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

		<link rel="icon" href="/icon.png" type="image/png">
		<link rel="icon" href="/icon.svg" type="image/svg+xml">
		<link rel="apple-touch-icon" href="/icon.png">

		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
		
		<script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>

		<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
		<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

		<script src="https://kit.fontawesome.com/4708ec5749.js" crossorigin="anonymous"></script>

		<%# Includes all stylesheet files in app/assets/stylesheets %>
		<%= stylesheet_link_tag :app %>
		<%= javascript_importmap_tags %>
	</head>

	<body>
		<%= yield %>

		<!-- Bootstrap 5 JS Bundle with Popper -->
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
	</body>
</html>

app/views/payment_types/_form.html.erb
<%= form_with(model: payment_type) do |form| %>
  <% if payment_type.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(payment_type.errors.count, "error") %> prohibited this payment_type from being saved:</h2>

      <ul>
        <% payment_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.textarea :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/payment_types/_payment_type.html.erb
<div id="<%= dom_id payment_type %>">
  <p>
    <strong>Name:</strong>
    <%= payment_type.name %>
  </p>

</div>

app/views/payment_types/edit.html.erb
<% content_for :title, "Editing payment type" %>

<h1>Editing payment type</h1>

<%= render "form", payment_type: @payment_type %>

<br>

<div>
  <%= link_to "Show this payment type", @payment_type %> |
  <%= link_to "Back to payment types", payment_types_path %>
</div>

app/views/payment_types/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Payment types" %>

<h1>Payment types</h1>

<div id="payment_types">
  <% @payment_types.each do |payment_type| %>
    <%= render payment_type %>
    <p>
      <%= link_to "Show this payment type", payment_type %>
    </p>
  <% end %>
</div>

<%= link_to "New payment type", new_payment_type_path %>

app/views/payment_types/new.html.erb
<% content_for :title, "New payment type" %>

<h1>New payment type</h1>

<%= render "form", payment_type: @payment_type %>

<br>

<div>
  <%= link_to "Back to payment types", payment_types_path %>
</div>

app/views/payment_types/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @payment_type %>

<div>
  <%= link_to "Edit this payment type", edit_payment_type_path(@payment_type) %> |
  <%= link_to "Back to payment types", payment_types_path %>

  <%= button_to "Destroy this payment type", @payment_type, method: :delete %>
</div>